name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: '5.1'
    - uses: leafo/gh-actions-luarocks@v4
      with:
        luarocksVersion: '3.7.0'
    - name: build
      run: luarocks make
    - name: test
      run: luarocks test
