name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: compute cache key suffix
      run: echo WOWLESS_CACHEKEY_SUFFIX=$(date -u +%Y%m%d%H) >> $GITHUB_ENV
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache
        key: cache-${{ env.WOWLESS_CACHEKEY_SUFFIX }}
        restore-keys: cache-
    - name: install deps
      run: sudo apt-get install -y libyaml-dev libzip-dev
    - name: setup
      run: bin/setup.sh
    - name: test
      run: bin/test.sh --exclude-tags=huge
