name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: cache
      uses: actions/cache@v2
      with:
        path: cache
        key: cache
    - name: setup
      run: bin/setup.sh
    - name: run
      run: bin/run.sh
    - name: upload rockspec
      run: bin/upload.sh ${{ secrets.LUAROCKS_API_KEY }}
