name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: setup
      run: ./setup.sh
    - name: run
      run: ./run.sh
